name: Deploy to GitHub-Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Volta
        uses: volta-cli/action@v4

      - name: Install Node.js
        run: volta install node

      - name: Install pnpm
        run: volta install pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Build project
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./build
          branch: gh-pages
          single-commit: true
